name: Deploy documentation

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: setup node and pnpm
              uses: dafnik/setup-node-pnpm@v5
              with:
                  pnpm: 10
                  node: 22
              # cwd: "."
              # install: false
              # install-ignore-scripts: false

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Generate typedoc documentation
              run: pnpm run doc

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: docs
                  token: ${{ secrets.ACCESS_TOKEN }}